### ISSUE TITLE
Please sign with strong name

### ISSUE THREAD

**Issue by wsteinbach** [DevExpress/BigQueryProvider#169]
I can not sign my app or use your package if you do not sign with a strong Name

12>CSC : warning CS8002: Die referenzierte Assembly "DevExpress.DataAccess.BigQuery, Version=1.4.0.1, Culture=neutral, PublicKeyToken=null" besitzt keinen starken Namen.

Thank you very much.

**Comment by Aristarh71** [comment]
Duplicate of #73
